### ISSUE TITLE
Searching for cards

### ISSUE THREAD

**Issue by gwill1010** [rwjdk/TrelloDotNet#40]
I want to search for a card by occurrence of text in the title.  The below works, but can I search by boardID & Open Cards?

                var client = new TrelloDotNet.TrelloClient(key, token);
   
                SearchRequest search = new SearchRequest("89914");
   
                var cardId = client.SearchAsync(search).GetAwaiter().GetResult();

                return cardId.ToString();

**Comment by rwjdk** [comment]
Wow, totally forgotten that I actually had implemented the search feature (properly because I never use it, as newly created items take some time before they can be search (aka dealbreaker in many situations)).

As for open cards you should be able to include in the search-term "is:open" to only get open cards (source: https://support.atlassian.com/trello/docs/searching-for-cards-all-boards/)

As for boards you need to specify in the search request the "BoardFilter" with the ids of the boards you wish to include

NB: Above is all from memory as I'm not near a PC as of this writing... If some of it does not work, let me know so I can investigqte further

**Comment by gwill1010** [comment]
Maybe when you have a chance you can help me out with the syntax?  I'm not having any luck.  This certainly doesn't work:
search.BoardFilter.BoardIds.Equals(boardId);
var cardId = client.SearchAsync(search).GetAwaiter().GetResult();

**Comment by rwjdk** [comment]
Here is an example of usage 

```var client = new TrelloClient(trelloApiKey, trelloToken);

var searchRequest = new SearchRequest("test is:open");
searchRequest.SearchOrganizations = false;
searchRequest.SearchBoards = false;
searchRequest.SearchCards = true;
searchRequest.BoardFilter = new SearchRequestBoardFilter("5c61e8231ce6c68845734a80", "ewedd322swsw8282"); //Only the boardIds one of these 2 boardIds

SearchResult searchResult = await client.SearchAsync(searchRequest);
```
